### ISSUE TITLE
Bluetooth sending data does not work

### ISSUE THREAD

**Issue by sjy5386** [red-light-tizen/Red-Light#1]
[0m[bt_socket_send_data] failed.
Required key not available

**Comment by sjy5386** [comment]
It may be a problem with my source code.
However, it may be a hardware problem or an operating system problem.

**Comment by sjy5386** [comment]
We bought a new Raspberry Pi.
Please test with a new device. @Kasania @Kanu1755

**Comment by Kanu1755** [comment]
I tested new Raspberry Pi with this issuue It didn't  works too so,I think we should be buy bluetooth module or ask tizenteam on slack it isn't  work @sjy5386 i will be upload results soon that why it didn't  works

**Comment by Kasania** [comment]
I Found messages when send fail.
That messages repeat 
 Please check this.

* D/BLUETOOTH_FRWK_API( 5542): bt-rfcomm-client.c: bluetooth_rfcomm_write(1337) > FD : 27
[31;1mE/red-light( 5542): [0m[bt_socket_send_data] failed.

* D/red-light( 5542): Required key not available

**Comment by Kasania** [comment]
I think this issue is related with method "bluetooth_rfcomm_write" in "BLUETOOTH_FRWK_API".

**Comment by Kanu1755** [comment]
Hmmmm..... @Kasania found that messages so I think RFCCOM WRITE SOCKET ERROR  @sjy5386 and might be not hardware problem I hope so...😂😂

**Comment by sjy5386** [comment]
Thank you for testing. 😉 @Kanu1755 @Kasania 
It's likely a problem with my source code. 😥
Because the three Raspberry Pis are unlikely to be defective.

**Comment by Kasania** [comment]
Fixed issue. @sjy5386 @Kanu1755
This issue caused by data length mismatch.
Desktop application is now read only 62 character.
So should be send 62 character include of null character.

**Comment by sjy5386** [comment]
![after](https://user-images.githubusercontent.com/13289043/64695928-3349a680-d4d8-11e9-9479-92c7291d8de3.jpg)
com-fort 😀

**Comment by Kasania** [comment]
Send Data Format
* yyyy;ddd;ssssssss;c;ppp;tttt;ooooo;aaaa;+ll.lllll;-ggg.ggggg;
* y : year
* d : day of year
* s : second of day
* c : condition
* p : pulse
* t : temperature
* o : SPO2
* a : activity
* l : latitude
* g : longitude

**Comment by sjy5386** [comment]
The data sending succeeded, but failed in the dlog. 😱

**Comment by Kasania** [comment]
I 'll check that asap.

**Comment by sjy5386** [comment]
> 
> 
> Send Data Format
> 
>     * yyyy;ddd;ssssssss;c;ppp;tttt;ooooo;aaaa;+ll.lllll;-ggg.ggggg;
> 
>     * y : year
> 
>     * d : day of year
> 
>     * s : second of day
> 
>     * c : condition
> 
>     * p : pulse
> 
>     * t : temperature
> 
>     * o : SPO2
> 
>     * a : activity
> 
>     * l : latitude
> 
>     * g : longitude

e.g.
2019;243;59123051;4;098;3750;09820;0230;+36.23422;-128.35869;

**Comment by Kasania** [comment]
We don't need fixed data length anymore.
