### ISSUE TITLE
Bluetooth socket connection requested callback does not work

### ISSUE THREAD

**Issue by sjy5386** [red-light-tizen/Red-Light#3]
I added a callback that check the Bluetooth connection request before accepting.
But it doesn't work.

**Comment by Kasania** [comment]
is this issue about bluetooth-frwk-test?

**Comment by Kasania** [comment]
This issue caused by untrusted device connection.
We have to add device to trusted device list.

**Comment by Kasania** [comment]
I add bond and authorize device function.
After first connection, we don't need user confirmation.

**Comment by sjy5386** [comment]
> The image we are using is a Tizen 5.5 Headed image. Headed images can be used in conjunction with a monitor with an HDMI cable. This image is said to establish a Bluetooth connection only by explicit consent from the policy. There is no way to make a direct connection without your explicit consent.
