### ISSUE TITLE
Hardware progress

### ISSUE THREAD

**Issue by sjy5386** [red-light-tizen/Red-Light#4]
- [x] Pulse & SPO2
- [x] Temperature
- [ ] Gyroscope
- [x] GPS

**Comment by sjy5386** [comment]
@Kanu1755 
Please commit into 'sensor-input' branch.
Do not create new repository.

**Comment by sjy5386** [comment]
### Interfaces
- Pulse & SPO2: I2C
- Temperature: SPI
- Gyroscope: SPI
- GPS: UART

**Comment by sjy5386** [comment]
peripheral i2c read & write
-5 Input/Output error

**Comment by Kasania** [comment]
Try removing *static* keyword from "peripheral_i2c_h pulse_h" in "sensor_pulse.c"

**Comment by sjy5386** [comment]
> 
> 
> Try removing _static_ keyword from "peripheral_i2c_h pulse_h" in "sensor_pulse.c"

It has nothing to do with it.

**Comment by sjy5386** [comment]
[MAX30100 산소포화도 센서 사용하기](https://blog.naver.com/antplustech/220861928556)
I saw and followed this article. And I rewrote the code for Tizen. But it doesn't work.

**Comment by sjy5386** [comment]
@Kanu1755 
Please check branch 'sensor'.
And give me GPS source code or commit it.

**Comment by Kasania** [comment]
We can use Pulse sensor.
