### ISSUE TITLE
LM35 CAZ and MAX 30100 Overheating Problem

### ISSUE THREAD

**Issue by Kanu1755** [red-light-tizen/Red-Light#5]
LM35 is too hot when I tested with RPI3
I solve this problem with Vdd and Vout on 4.4k register
but I think It will be not good at work normally, So I will test this temp sensor and MAX30100 PULSE sensor
This work is take it many time I think 
I will check this problem asap sorry

**Comment by sjy5386** [comment]
It's so hot! 😈

**Comment by Kasania** [comment]
We Add more ground wire and That is work.
